### ISSUE TITLE
Can't trigger MessageRecieved Callback

### ISSUE THREAD

**Issue by Zettersten** [ironyx/simplsockets#3]
When performing `SendRecieve`, I'm getting my data as expected.

However when I perform a `Send`, my callback doesnt get fired.

I've stepped through the project.

Perhaps you can help me debug?

![image](https://cloud.githubusercontent.com/assets/183147/9064326/0394ca78-3a9a-11e5-9f2b-2ed7e09b7898.png)

I am getting lost in this MultiPlexer stuff.

I know my events are bound correctly because my errors are bubbling up correctly.

My send looks something like:

![image](https://cloud.githubusercontent.com/assets/183147/9064400/4fb69102-3a9a-11e5-8fac-a9ffbf620a00.png)

What happens after `SignalMultplexer`? Specifically the event reset.

I'm lost!

**Comment by haneytron** [comment]
I suspect this was a bug in an older version. Closing for now, please re-open if you are still experiencing the issue! And sorry for the long delay in reply.
